<?php

/**
 * @file
 * Handles the creation/display of islandora:sp-ohCModel objects.
 */

/**
 * Implements hook_menu().
 */
function islandora_oral_history_menu() {
  return array(
    'admin/islandora/solution_pack_config/oral_history' => array(
      'title' => 'An Oral History Solution Pack',
      'description' => 'Select player.',
      'page callback' => 'drupal_get_form',
      'access arguments' => array('administer site configuration'),
      'page arguments' => array('islandora_oral_history_admin'),
      'file' => 'includes/admin.form.inc',
      'type' => MENU_NORMAL_ITEM,
    ),
  );
}

/**
 * Implements hook_islandora_required_objects().
 */
function islandora_oral_history_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'islandora_oral_history');
  // OH Content Model.
  $oh_content_model = $connection->repository->constructObject('islandora:sp-ohCModel');
  $oh_content_model->owner = 'fedoraAdmin';
  $oh_content_model->label = 'Islandora OH Content Model';
  $oh_content_model->models = 'fedora-system:ContentModel-3.0';
  // DS-COMPOSITE-MODEL Datastream.
  $datastream = $oh_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'X');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'application/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_oral_history_ds_composite_model.xml", FALSE);
  $oh_content_model->ingestDatastream($datastream);
  // Audio Collection.
  $oh_collection = $connection->repository->constructObject('islandora:oh_collection');
  $oh_collection->owner = 'fedoraAdmin';
  $oh_collection->label = 'Audio Collection';
  $oh_collection->models = 'islandora:collectionCModel';
  $oh_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  // Collection Policy Datastream.
  $datastream = $oh_collection->constructDatastream('COLLECTION_POLICY', 'X');
  $datastream->label = 'Collection policy';
  $datastream->mimetype = 'application/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_oral_history_collection_policy.xml", FALSE);
  $oh_collection->ingestDatastream($datastream);
  // TN Datastream.
  $datastream = $oh_collection->constructDatastream('TN', 'M');
  $datastream->label = 'Thumbnail';
  $datastream->mimetype = 'image/png';
  $datastream->setContentFromFile("$module_path/images/folder.png", FALSE);
  $oh_collection->ingestDatastream($datastream);
  return array(
    'islandora_oral_history' => array(
      'title' => 'Islandora oh',
      'objects' => array(
        $oh_content_model,
        $oh_collection,
      ),
    ),
  );
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_oral_history_islandora_sp_ohCModel_islandora_view_object($object, $page_number, $page_size) {
  $output = theme('islandora_oral_history', array('islandora_object' => $object));
  return array('' => $output);
}

/**
 * Implements hook_islandora_xml_form_builder_forms().
 */
function islandora_oral_history_islandora_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_oral_history');
  return array(
    'Audio MODS form' => array(
      'form_file' => "$module_path/xml/islandora_oral_history_form_mods.xml",
    ),
  );
}

/**
 * Implements hook_islandora_xml_form_builder_form_associations().
 */
function islandora_oral_history_islandora_xml_form_builder_form_associations() {
  return array(
    'islandora_oral_history_mods_form' => array(
      'content_model' => 'islandora:sp-ohCModel',
      'form_name' => 'Audio MODS form',
      'dsid' => 'MODS',
      'title_field' => array('titleInfo', 'title'),
      'transform' => 'mods_to_dc.xsl',
      'template' => FALSE,
    ),
  );
}

/**
 * Implements hook_theme().
 */
function islandora_oral_history_theme($existing, $type, $theme, $path) {
  return array(
    'islandora_oral_history' => array(
      'template' => 'theme/islandora-oh',
      'pattern' => 'islandora_oral_history__',
      'variables' => array('islandora_object' => NULL),
    ),
  );
}

/**
 * Implements template_preprocess_hook().
 */
function islandora_oral_history_preprocess_islandora_oral_history(array &$variables) {
  drupal_add_js('misc/form.js');
  drupal_add_js('misc/collapse.js');
  $islandora_object = $variables['islandora_object'];
  $repository = $islandora_object->repository;
  module_load_include('inc', 'islandora', 'includes/datastream');
  module_load_include('inc', 'islandora', 'includes/utilities');
  module_load_include('inc', 'islandora', 'includes/metadata');

  // We should eventually remove the DC object and dc_array code as it only
  // exists to not break legacy implementations.
  try {
    if (isset($islandora_object['DC']) && islandora_datastream_access(ISLANDORA_VIEW_OBJECTS, $islandora_object['DC'])) {
      $dc = $islandora_object['DC']->content;
      $dc_object = DublinCore::importFromXMLString($dc);
    }
  }
  catch (Exception $e) {
    drupal_set_message(t('Error retrieving object %s %t', array('%s' => $islandora_object->id, '%t' => $e->getMessage())), 'error', FALSE);
  }
  $variables['islandora_dublin_core'] = isset($dc_object) ? $dc_object : NULL;
  $variables['dc_array'] = isset($dc_object) ? $dc_object->asArray() : array();
  $variables['islandora_object_label'] = $islandora_object->label;
  $variables['theme_hook_suggestions'][] = 'islandora_oral_history__' . str_replace(':', '_', $islandora_object->id);
  $variables['parent_collections'] = islandora_get_parents_from_rels_ext($islandora_object);
  $variables['metadata'] = islandora_retrieve_metadata_markup($islandora_object);
  $variables['description'] = islandora_retrieve_description_markup($islandora_object);

  // Start getting parameters for the player...
  $oh_params = array(
    "pid" => $islandora_object->id,
  );
  // Thumbnail.
  if (isset($islandora_object['TN']) && islandora_datastream_access(ISLANDORA_VIEW_OBJECTS, $islandora_object['TN'])) {
    $tn_url = url("islandora/object/{$islandora_object->id}/datastream/TN/view");
    $params = array(
      'title' => $islandora_object->label,
      'path' => $tn_url,
    );
    $variables['islandora_thumbnail_img'] = theme('image', $params);

    $oh_params += array(
      'tn' => $tn_url,
    );
  }

  // Audio player.
  // Determine whether to attempt to use the OBJ or PROXY_MP3.
  module_load_include('inc', 'islandora_oral_history', 'includes/utilities');
  $dsid = !isset($islandora_object['PROXY_MP3']) &&
    variable_get('islandora_oral_history_obj_fallback', TRUE) &&
    isset($islandora_object['OBJ']) &&
    islandora_oral_history_datastream_valid_for_playback($islandora_object['OBJ']) ? 'OBJ' : 'PROXY_MP3';

  if (islandora_datastream_access(ISLANDORA_VIEW_OBJECTS, $islandora_object[$dsid])) {
    $oh_url = url("islandora/object/{$islandora_object->id}/datastream/$dsid", array('absolute' => TRUE));

    $oh_params += array(
      "url" => $oh_url,
      "mime" => 'audio/mpeg',
    );

    module_load_include('inc', 'islandora', 'includes/solution_packs');
    $viewer = islandora_get_viewer($oh_params, 'islandora_oral_history_viewers', $islandora_object);

    if ($viewer) {
      $variables['islandora_content'] = $viewer;
    }
    elseif (isset($variables['islandora_thumbnail_img'])) {
      $variables['islandora_content'] = l($variables['islandora_thumbnail_img'], $oh_url, array('html' => TRUE));
    }
    else {
      $variables['islandora_content'] = l($islandora_object->label, $oh_url);
    }
  }
}

/**
 * Implements hook_islandora_ingest_steps().
 */
function islandora_oral_history_islandora_sp_ohcmodel_islandora_ingest_steps() {
  return array(
    'islandora_oral_history_upload' => array(
      'weight' => 10,
      'type' => 'form',
      'form_id' => 'islandora_oral_history_oh_upload_form',
      'module' => 'islandora_oral_history',
      'file' => 'includes/oh_upload.form.inc',
    ),
  );
}

/**
 * Implements hook_CMODEL_PID_islandora_derivative().
 */
function islandora_oral_history_islandora_sp_ohcmodel_islandora_derivative() {
  $derivative_list = array(
    array(
      'source_dsid' => NULL,
      'destination_dsid' => 'TN',
      'weight' => 1,
      'function' => array(
        'islandora_oral_history_create_thumbnail',
      ),
      'file' => drupal_get_path('module', 'islandora_oral_history') . '/includes/derivatives.inc',
    ),
  );
  if (!variable_get('islandora_oral_history_defer_derivatives_on_ingest', FALSE)) {
    $derivative_list[] = array(
      'source_dsid' => 'OBJ',
      'destination_dsid' => 'PROXY_MP3',
      'weight' => '0',
      'function' => array(
        'islandora_oral_history_create_mp3',
      ),
      'file' => drupal_get_path('module', 'islandora_oral_history') . '/includes/derivatives.inc',
    );
  }
  return $derivative_list;
}
